// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddFieldRequest
    {
        /// <summary>
        /// Initializes a new instance of the AddFieldRequest class.
        /// </summary>
        public AddFieldRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddFieldRequest class.
        /// </summary>
        public AddFieldRequest(FieldRequest fieldRequest = default(FieldRequest), DiscountRequest discountRequest = default(DiscountRequest), IList<ImageFieldRequest> pictureFieldRequest = default(IList<ImageFieldRequest>))
        {
            FieldRequest = fieldRequest;
            DiscountRequest = discountRequest;
            PictureFieldRequest = pictureFieldRequest;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldRequest")]
        public FieldRequest FieldRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "discountRequest")]
        public DiscountRequest DiscountRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pictureFieldRequest")]
        public IList<ImageFieldRequest> PictureFieldRequest { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FieldRequest != null)
            {
                FieldRequest.Validate();
            }
            if (DiscountRequest != null)
            {
                DiscountRequest.Validate();
            }
            if (PictureFieldRequest != null)
            {
                foreach (var element in PictureFieldRequest)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
