// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DiscountModel
    {
        /// <summary>
        /// Initializes a new instance of the DiscountModel class.
        /// </summary>
        public DiscountModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DiscountModel class.
        /// </summary>
        public DiscountModel(int? id = default(int?), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? updatedDate = default(System.DateTime?), int? fieldId = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), double? percentage = default(double?), string detail = default(string))
        {
            Id = id;
            CreatedDate = createdDate;
            UpdatedDate = updatedDate;
            FieldId = fieldId;
            StartDate = startDate;
            EndDate = endDate;
            Percentage = percentage;
            Detail = detail;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedDate")]
        public System.DateTime? UpdatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldId")]
        public int? FieldId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public System.DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endDate")]
        public System.DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percentage")]
        public double? Percentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "detail")]
        public string Detail { get; set; }

    }
}
