// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DistrictModel
    {
        /// <summary>
        /// Initializes a new instance of the DistrictModel class.
        /// </summary>
        public DistrictModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DistrictModel class.
        /// </summary>
        public DistrictModel(int? id = default(int?), string name = default(string), int? provinceId = default(int?), ProvinceModel provinceModel = default(ProvinceModel))
        {
            Id = id;
            Name = name;
            ProvinceId = provinceId;
            ProvinceModel = provinceModel;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provinceId")]
        public int? ProvinceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provinceModel")]
        public ProvinceModel ProvinceModel { get; set; }

    }
}
