// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FieldDetailDto
    {
        /// <summary>
        /// Initializes a new instance of the FieldDetailDto class.
        /// </summary>
        public FieldDetailDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FieldDetailDto class.
        /// </summary>
        public FieldDetailDto(int? id = default(int?), string name = default(string), double? price = default(double?), bool? isOpen = default(bool?), double? percentage = default(double?), IList<ImageFieldDto> imageFieldDto = default(IList<ImageFieldDto>))
        {
            Id = id;
            Name = name;
            Price = price;
            IsOpen = isOpen;
            Percentage = percentage;
            ImageFieldDto = imageFieldDto;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isOpen")]
        public bool? IsOpen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percentage")]
        public double? Percentage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "imageFieldDto")]
        public IList<ImageFieldDto> ImageFieldDto { get; set; }

    }
}
