// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GrahpDto
    {
        /// <summary>
        /// Initializes a new instance of the GrahpDto class.
        /// </summary>
        public GrahpDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GrahpDto class.
        /// </summary>
        public GrahpDto(int? days = default(int?), int? months = default(int?), int? years = default(int?))
        {
            Days = days;
            Months = months;
            Years = years;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "days")]
        public int? Days { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "months")]
        public int? Months { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "years")]
        public int? Years { get; set; }

    }
}
