// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamServices.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentDto
    {
        /// <summary>
        /// Initializes a new instance of the PaymentDto class.
        /// </summary>
        public PaymentDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentDto class.
        /// </summary>
        public PaymentDto(int? reservationId = default(int?), string image = default(string), double? amount = default(double?), System.DateTime? date = default(System.DateTime?), bool? isFullAmount = default(bool?))
        {
            ReservationId = reservationId;
            Image = image;
            Amount = amount;
            Date = date;
            IsFullAmount = isFullAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reservationId")]
        public int? ReservationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image")]
        public string Image { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFullAmount")]
        public bool? IsFullAmount { get; set; }

    }
}
