// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentModel
    {
        /// <summary>
        /// Initializes a new instance of the PaymentModel class.
        /// </summary>
        public PaymentModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentModel class.
        /// </summary>
        public PaymentModel(int? id = default(int?), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? updatedDate = default(System.DateTime?), int? reservationId = default(int?), string image = default(string), double? amount = default(double?), System.DateTime? date = default(System.DateTime?), bool? isFullAmount = default(bool?))
        {
            Id = id;
            CreatedDate = createdDate;
            UpdatedDate = updatedDate;
            ReservationId = reservationId;
            Image = image;
            Amount = amount;
            Date = date;
            IsFullAmount = isFullAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedDate")]
        public System.DateTime? UpdatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reservationId")]
        public int? ReservationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image")]
        public string Image { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFullAmount")]
        public bool? IsFullAmount { get; set; }

    }
}
