// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamServices.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProblemsDetailDto
    {
        /// <summary>
        /// Initializes a new instance of the ProblemsDetailDto class.
        /// </summary>
        public ProblemsDetailDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProblemsDetailDto class.
        /// </summary>
        public ProblemsDetailDto(string detail = default(string), IDictionary<string, object> extensions = default(IDictionary<string, object>), string instance = default(string), int? status = default(int?), string title = default(string), string type = default(string), int? errorCode = default(int?))
        {
            Detail = detail;
            Extensions = extensions;
            Instance = instance;
            Status = status;
            Title = title;
            Type = type;
            ErrorCode = errorCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "detail")]
        public string Detail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extensions")]
        public IDictionary<string, object> Extensions { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instance")]
        public string Instance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public int? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public int? ErrorCode { get; set; }

    }
}
