// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ReservationDetailDto
    {
        /// <summary>
        /// Initializes a new instance of the ReservationDetailDto class.
        /// </summary>
        public ReservationDetailDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReservationDetailDto class.
        /// </summary>
        public ReservationDetailDto(int? id = default(int?), bool? approvalStatus = default(bool?), string userName = default(string), string storeName = default(string), string contactMobile = default(string), System.DateTime? startTime = default(System.DateTime?), System.DateTime? stopTime = default(System.DateTime?), string fieldName = default(string), double? pricePerHour = default(double?), bool? isFullAmount = default(bool?), IList<PaymentModel> paymentModel = default(IList<PaymentModel>), double? amountForPay = default(double?))
        {
            Id = id;
            ApprovalStatus = approvalStatus;
            UserName = userName;
            StoreName = storeName;
            ContactMobile = contactMobile;
            StartTime = startTime;
            StopTime = stopTime;
            FieldName = fieldName;
            PricePerHour = pricePerHour;
            IsFullAmount = isFullAmount;
            PaymentModel = paymentModel;
            AmountForPay = amountForPay;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "approvalStatus")]
        public bool? ApprovalStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeName")]
        public string StoreName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactMobile")]
        public string ContactMobile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stopTime")]
        public System.DateTime? StopTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldName")]
        public string FieldName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pricePerHour")]
        public double? PricePerHour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFullAmount")]
        public bool? IsFullAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentModel")]
        public IList<PaymentModel> PaymentModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountForPay")]
        public double? AmountForPay { get; set; }

    }
}
