// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamServices.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReservationRequest
    {
        /// <summary>
        /// Initializes a new instance of the ReservationRequest class.
        /// </summary>
        public ReservationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReservationRequest class.
        /// </summary>
        public ReservationRequest(int? storeId = default(int?), int? userId = default(int?), int? fieldId = default(int?), System.DateTime? startTime = default(System.DateTime?), System.DateTime? stopTime = default(System.DateTime?))
        {
            StoreId = storeId;
            UserId = userId;
            FieldId = fieldId;
            StartTime = startTime;
            StopTime = stopTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeId")]
        public int? StoreId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public int? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldId")]
        public int? FieldId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stopTime")]
        public System.DateTime? StopTime { get; set; }

    }
}
