// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamServices.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubDistrictModel
    {
        /// <summary>
        /// Initializes a new instance of the SubDistrictModel class.
        /// </summary>
        public SubDistrictModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubDistrictModel class.
        /// </summary>
        public SubDistrictModel(int? id = default(int?), string name = default(string), double? latitude = default(double?), double? longitude = default(double?), int? districtId = default(int?), DistrictModel districtModel = default(DistrictModel))
        {
            Id = id;
            Name = name;
            Latitude = latitude;
            Longitude = longitude;
            DistrictId = districtId;
            DistrictModel = districtModel;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "districtId")]
        public int? DistrictId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "districtModel")]
        public DistrictModel DistrictModel { get; set; }

    }
}
