// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace JongSnamService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateReservationRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateReservationRequest class.
        /// </summary>
        public UpdateReservationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateReservationRequest class.
        /// </summary>
        public UpdateReservationRequest(System.DateTime? startTime = default(System.DateTime?), System.DateTime? stopTime = default(System.DateTime?))
        {
            StartTime = startTime;
            StopTime = stopTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public System.DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stopTime")]
        public System.DateTime? StopTime { get; set; }

    }
}
